version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission_user #optional
      - PASS=transmission_password #optional
    volumes:
      - ./../data/config:/config
      - ./../data/downloads:/downloads
      - ./../data/watch:/watch
    ports:
      - 9091:9091
      - 51410:51410
      - 51410:51410/udp
    restart: always
